version: '3'
services:
  mysqlstandalone:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=#Ash@123
      - MYSQL_DATABASE=hibernate
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
  app:
    depends_on:
      - mysqlstandalone
    build: .
    ports:
      - 8080:8082

volumes:
  db-data: